repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [-L THIRDPARTY] # Configuration word needed in pyproject.toml

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        exclude: "tests/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Add here the check of github workflow when needed (Actually not need on ADO)

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: v0.4.3
    hooks:
      - id: add-license-headers
